transcription_task:
  description: >
    Transcribe the video at the provided URL {URL}.
  expected_output: >
    Text corresponding to the audio output from the provided video.
  agent: transcriber

domain_parsing_task:
  description: >
    Parse the domain and subdomain from the received text.
  expected_output: >
    Domain, subdomain and the received text.
    # JSON Output: The output should be in the following JSON structure: 
    # 'domain': '...', 'subdomain': '...', 'text': ...
  agent: domain_parser

quiz_generation_task:
  description: >
    Generate multiple-choice quiz questions about the information included in the text received.
  expected_output: >
    Multiple Choice Question (MCQ) Format: The question should have one correct answer and three incorrect but plausible
    distractors.
    JSON Output: The output should be in the following JSON structure: 'question': '...', 'options': '...', 'correct_answer': '...', 'explanation': '...'
  agent: quiz_generator
