transcription_task:
  description: >
    Transcribe the video at the provided URL {URL}.
  expected_output: >
    Text corresponding to the audio output from the provided video.
  agent: transcriber

quiz_generation_task:
  description: >
    Review the text you received and generate questions about the information included in the text.
    Consult any internet resources necessary to thoroughly test the user's knowedge of the concepts mentioned in the text.
    Make sure the questions are well-explained, concise, contains any and all relevant information and that the answers provided are correct.
  expected_output: >
    Multiple Choice Question (MCQ) Format: The question should have one correct answer and three incorrect but plausible
    distractors.
    JSON Output: The output should be in the following JSON structure: 'question': '...', 'explanation': '...'
  agent: quiz_generator
